#!/bin/bash
total_mem=`free -m | grep Mem | awk '{print  $2}'`
free_mem=`free -m | grep Mem | awk '{print  $4}'`
echo "Total memory is $total_mem MB and free memory is $free_mem MB"
if [ $free_mem -lt 0 ]; then
        echo "Unknown state" && exit 3
elif [ $free_mem -lt 100 ]; then
        echo "Critical, free memory is $free_mem MB" && exit 2
elif [ $free_mem -lt 500 ]; then
        echo "Warning, free memory is $free_mem MB" && exit 1
elif [ $free_mem -gt 500 ]; then
        echo "Warning, free memory is $free_mem MB" && exit 0
fi

