#!/bin/bash
#Usage of CPU
#echo Load of CPU is `top -b -n1 | grep "Cpu(s)" | awk '{print $1 $2}'`
#Total Memory
#echo Total memory is `free -h | grep Mem | awk '{print $1 $2}'`
#Free Memory
#echo Free memory is `free -h | grep Mem | awk '{print $1 $4}'`
cpu_load=`top -b -n1 | grep "Cpu(s)" | awk '{print $2}'`
if [ $cpu_load -lt 0 ]; then
	echo "Unknown current CPU load" && exit 3
elif [ $cpu_load -lt 75 ]; then
	echo "OK, current CPU load is $cpu_load%" && exit 0
elif [ $cpu_load -gt 75 ]; then 
	echo "Warning, current CPU load is $cpu_load%" && exit 1
elif [ $cpu_load -gt 90 ]; then
	echo "Critical, current CPU load is $cpu_load%" && exit 2
fi
